/*
 * Deals Table
 * ----------
 * Manages NIL deals between athletes and clients.
 * Tracks deal status, payments, and terms.
 */

CREATE TABLE `deals` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uniqueID` varchar(30) DEFAULT NULL COMMENT 'Unique id number for each deal.',
  `paid` tinyint DEFAULT '0' COMMENT '''1'' if deal has been paid. ''0'' if unpaid.',
  `charge_id` varchar(255) DEFAULT NULL COMMENT 'The charge id generated by Stripe.',
  `campaign_id` varchar(30) DEFAULT NULL COMMENT 'Value references ''campaigns(id)''',
  `status` enum('saved','deleted','cart','under_review','approved','athlete_accepted','athlete_declined','expired','under_dispute','complete') DEFAULT NULL COMMENT 'Current status of each deal.',
  `secondary_status` enum('content_algo_flagged','content_human_flagged','fail_algo','pass_algo','pass_manual','fail_manual','athlete_failure','pending_complete','client_complete','client_fail','retention_closed','escalated','paid','mediation_pending','mediation_client','mediation_athlete','mediation_split','mediation_other') DEFAULT NULL COMMENT 'Current secondary status of each deal if applicable.',
  `athlete_id` int DEFAULT NULL COMMENT 'Value references ''users(id)''',
  `service_id` int DEFAULT NULL COMMENT 'Value references ''nilUsers(id)''',
  `platform_service_id` int DEFAULT NULL COMMENT 'Value references ''nilServices(id)''',
  `client_id` varchar(30) DEFAULT NULL COMMENT '''id'' of the client. If value is only numerical then it references the ''id'' from the ''users'' table. If value begings with ''B_'' the the client is a brand and the value references ''uniqueID(brands)''. If value begins with ''C_'' then the client is a NIL collective and the value references ''uniqueID(collectives)''.',
  `submitter_id` varchar(30) DEFAULT NULL COMMENT 'The ''id'' of the person that send the deal. Value references ''users(id)''.',
  `overview` text COMMENT 'Overview of the NIL deal.',
  `overview_content_id` varchar(26) DEFAULT NULL COMMENT 'Value references ''content_unique_id(content_moderation)''',
  `time_sensitive` text COMMENT 'Input from the user regarding the time sensitive nature of the deal.',
  `time_sensitive_content_id` varchar(26) DEFAULT NULL COMMENT 'Value references ''content_unique_id(content_moderation)''',
  `start_date` date DEFAULT NULL COMMENT 'Start date of the NIL deal.',
  `end_date` date DEFAULT NULL COMMENT 'End date of the NIL deal.',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Date the NIL was created.',
  `price` int DEFAULT NULL COMMENT 'Price of the NIL deal.',
  `best_offer` int DEFAULT NULL COMMENT 'Price of the NIL deal if a ''Best Offer'' price has been submitted.',
  `tip_added` tinyint DEFAULT '0' COMMENT 'Has the client added a tip to the NIL deal? ''1'' if YES. ''0'' if NO.',
  `tip_amount` int DEFAULT '0' COMMENT 'Amount of the tip added by the client.',
  `expedite` tinyint DEFAULT '0' COMMENT 'Has the client paid to have the deal expedited? ''1'' if YES. ''0'' if NO.',
  `expedite_amount` int DEFAULT '0' COMMENT 'Cost of the expedited services.',
  `service_fee` int DEFAULT NULL COMMENT 'Amount charged for the service fee on this deal.',
  `service_fee_percent` decimal(5,3) DEFAULT NULL COMMENT 'Percentage charged for the service fee.',
  `total` int DEFAULT NULL COMMENT 'Total amount charged for the NIL deal.',
  `timestamp_athlete_accepted` int DEFAULT NULL COMMENT 'The timestamp that the athlete accepted to work this NIL deal.',
  `timestamp_athlete_declined` int DEFAULT NULL COMMENT 'The timestamp that the athlete declined to work this NIL deal.',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
