name: EC2 Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Test connection
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connection successful!'"
          
          # First ensure the directory exists and we have proper permissions
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            sudo mkdir -p /var/www/html &&
            sudo chown -R $EC2_USER:$EC2_USER /var/www/html
          "
          
          # Copy ALL files to EC2
          scp -r -i private_key.pem ./* ./.* $EC2_USER@$EC2_HOST:/var/www/html/ 2>/dev/null || true
          
          # Set proper web permissions and verify files
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            echo 'Uploaded files:' &&
            ls -la /var/www/html/ &&
            sudo chown -R www-data:www-data /var/www/html/ &&
            sudo chmod -R 755 /var/www/html/ &&
            sudo find /var/www/html/ -type f -exec chmod 644 {} \;
          "
          
          echo "Deployment completed successfully!"

      - name: Cleanup
        if: always()
        run: |
          rm -f private_key.pem
          echo "Cleanup completed"