name: EC2 Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Test connection
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connection successful!'"
          
          # Create directories if they don't exist
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            sudo mkdir -p /var/www/html
          "
          
          # Copy files to their respective locations
          rsync -av --exclude='.git*' --exclude='private_key.pem' -e "ssh -i private_key.pem" ./public/ $EC2_USER@$EC2_HOST:/var/www/html/
          rsync -av --exclude='.git*' --exclude='private_key.pem' --exclude='public' -e "ssh -i private_key.pem" ./ $EC2_USER@$EC2_HOST:/var/www/
          
          # Set correct permissions
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            # First set private /var/www permissions
            sudo chown -R $EC2_USER:$EC2_USER /var/www &&
            sudo chmod 750 /var/www &&
            
            # Then set public /var/www/html permissions
            sudo chown -R apache:apache /var/www/html &&
            sudo chmod -R 755 /var/www/html &&
            sudo find /var/www/html -type f -exec chmod 644 {} \;
          "
          
          echo "Deployment completed successfully!"

      - name: Cleanup
        if: always()