name: EC2 Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: /home/ubuntu/app  # Default path, can be overridden by secrets
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH || '/home/ubuntu/app' }}
        run: |
          # Debug: Print variables (masking sensitive data)
          echo "Deploying as user: $EC2_USER"
          echo "Deploying to path: $DEPLOY_PATH"
          
          # Test connection
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connection successful!'"
          
          # Create deploy directory with explicit path
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "sudo mkdir -p /home/ubuntu/app && sudo chown $EC2_USER:$EC2_USER /home/ubuntu/app"
          
          # Copy files to EC2
          scp -i private_key.pem -r ./* $EC2_USER@$EC2_HOST:/home/ubuntu/app/
          
          echo "Deployment completed successfully!"

      - name: Cleanup
        if: always()
        run: |
          rm -f private_key.pem
          echo "Cleanup completed"