name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ -d "/var/www/html/.git" ]; then
              cd /var/www/html && git pull
            else
              rm -rf /var/www/html && git clone https://github.com/your-username/your-repo.git /var/www/html
            fi
