name: EC2 Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Test connection
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connection successful!'"
          
          # Create necessary directories and set initial permissions
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            sudo mkdir -p /var/www/html &&
            sudo chown -R $EC2_USER:$EC2_USER /var/www
          "
          
          # Copy public files to /var/www/html
          rsync -av --exclude='.git*' --exclude='private_key.pem' -e "ssh -i private_key.pem" ./public/ $EC2_USER@$EC2_HOST:/var/www/html/
          
          # Copy everything else (excluding public directory and other unnecessary files)
          rsync -av --exclude='.git*' --exclude='private_key.pem' --exclude='public' -e "ssh -i private_key.pem" ./ $EC2_USER@$EC2_HOST:/var/www/
          
          # Set proper permissions
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            # Set public directory permissions (readable by web server)
            sudo chmod -R 755 /var/www/html/ &&
            sudo find /var/www/html/ -type f -exec chmod 644 {} \; &&
            
            # Set private directory permissions (not accessible via web)
            sudo chmod -R 750 /var/www/ &&
            sudo find /var/www/ -type f -exec chmod 640 {} \; &&
            sudo chmod -R 755 /var/www/html/ &&
            sudo find /var/www/html/ -type f -exec chmod 644 {} \; &&
            
            # Verify deployments
            echo 'Public files (html):' &&
            ls -la /var/www/html/ &&
            echo 'Private files (www):' &&
            ls -la /var/www/
          "
          
          echo "Deployment completed successfully!"

      - name: Cleanup
        if: always()
        run: |
          rm -f private_key.pem
          echo "Cleanup completed"