# EC2 Deployment Workflow
#
# Overview:
# This workflow automates deployment of a web application to an Amazon EC2 instance,
# separating public content from application code for improved security.
#
# Trigger: Push to main branch
# Environment: Ubuntu Latest
#
# Detailed Process:
# 1. Repository Checkout
#    - Fetches repository code using actions/checkout@v2
#
# 2. SSH Key Creation
#    - Creates private key file from EC2_PRIVATE_KEY secret
#    - Sets 600 permissions for SSH usage
#
# 3. Connection Testing
#    - Verifies connectivity to EC2 instance
#
# 4. Directory Preparation
#    - Creates and sets ownership for:
#      - /var/www (protected application code)
#      - /var/www/public (publicly accessible web root)
#
# 5. File Deployment
#    - Uploads files to the server
#    - Excluded Files/Directories:
#      - .git* files and directories
#      - .github directory
#      - /database directory
#      - .clinerules
#      - .gitattributes and .gitignore
#
# 6. Composer Dependencies Installation
#    - Runs composer install in production mode
#    - Installs packages to /var/www/vendor
#
# 7. Permission Management
#    - Sets secure permissions for application directories
#    - Ensures web server can access public content
#
# 8. PHP Cache Clearing
#    - Clears OPcache and APCu if available
#
# 9. Service Restart
#    - Restarts PHP services (PHP-FPM or PHP)
#    - Restarts Apache web server
#
# 10. File Cache Refresh
#    - Touches all PHP files to refresh file-based caches
#
# 11. Cleanup
#    - Removes temporary private key file
#
# Required Secrets:
# - EC2_PRIVATE_KEY: SSH private key for EC2 access
# - EC2_USER: Username for EC2 connection
# - EC2_HOST: Hostname or IP address of EC2 instance
#
name: EC2 Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Test connection
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connection successful!'"
          
          # Ensure directories exist with proper permissions
          echo "Setting up directory structure..."
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            # Create directories if they don't exist
            sudo mkdir -p /var/www
            sudo mkdir -p /var/www/public
            
            # Set ownership to the web server user (typically www-data for Apache)
            sudo chown -R $EC2_USER:www-data /var/www
            
            # Set base permissions
            sudo chmod -R 750 /var/www          # rwxr-x--- (owner can read/write/execute, group can read/execute)
            sudo chmod -R 755 /var/www/public   # rwxr-xr-x (owner can read/write/execute, group and others can read/execute)
          "
          
          # Upload all files with exclusions
          echo "Uploading repository contents..."
          rsync -av \
            --exclude='.git*' \
            --exclude='.gitattributes' \
            --exclude='.gitignore' \
            --exclude='private_key.pem' \
            --exclude='docs' \
            --exclude='.github' \
            --exclude='database' \
            --exclude='.clinerules' \
            -e "ssh -i private_key.pem" \
            ./ $EC2_USER@$EC2_HOST:/var/www/
          
          # Check for Composer and install if needed, then run Composer install
          echo "Checking for Composer and installing dependencies..."
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            # Check if Composer is installed
            if ! command -v composer &> /dev/null; then
              echo 'Composer not found, installing...'
              # Create directory for Composer
              mkdir -p ~/.composer
              
              # Download Composer installer
              curl -sS https://getcomposer.org/installer -o composer-setup.php
              
              # Install Composer globally
              sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
              
              # Clean up installer
              rm composer-setup.php
              
              echo 'Composer installed successfully!'
            else
              echo 'Composer is already installed'
            fi
            
            # Install dependencies
            cd /var/www &&
            composer install \
              --no-dev \
              --classmap-authoritative \
              --no-interaction \
              --prefer-dist
          "
          
          # Set additional proper permissions for specific file types
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            echo 'Setting secure file permissions...' &&
            
            # Make sure files are not executable but are readable
            sudo find /var/www -type f -exec chmod 640 {} \;             # rw-r----- (owner can read/write, group can read)
            sudo find /var/www/public -type f -exec chmod 644 {} \;      # rw-r--r-- (owner can read/write, group and others can read)
            
            # Script files should be executable for the owner and group
            sudo find /var/www -name '*.sh' -exec chmod 750 {} \;        # rwxr-x--- (owner can read/write/execute, group can read/execute)
            
            # Ensure public directory is accessible
            sudo chmod 755 /var/www/public                               # rwxr-xr-x
            
            # Verify file permissions
            echo 'Verifying file permissions:' &&
            ls -la /var/www/ &&
            ls -la /var/www/public/
          "
          
          # Clear PHP caches and restart services
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            echo 'Clearing PHP caches and restarting services...' &&
            # Clear OPcache if enabled
            if php -r 'echo (int)function_exists(\"opcache_reset\");'; then
              php -r 'opcache_reset();'
              echo 'OPcache cleared successfully!'
            fi &&
            # Clear APCu cache if installed
            if php -r 'echo (int)function_exists(\"apcu_clear_cache\");'; then
              php -r 'apcu_clear_cache();'
              echo 'APCu cache cleared successfully!'
            fi &&
            # Force restart PHP services regardless of current status
            echo 'Restarting PHP services...' &&
            # Try PHP-FPM restart (common in modern setups)
            sudo systemctl restart php*-fpm 2>/dev/null || echo 'No PHP-FPM service found' &&
            # Try PHP service restart (for systems using traditional PHP module)
            sudo service php* restart 2>/dev/null || echo 'No PHP service found' &&
            # Force restart Apache regardless of current status
            echo 'Restarting Apache...' &&
            sudo systemctl restart apache2 2>/dev/null || sudo service apache2 restart 2>/dev/null || echo 'Apache restart attempted' &&
            # Clear PHP file cache by touching files if needed
            find /var/www -name '*.php' -exec touch {} \; &&
            echo 'PHP files touched to refresh file cache' &&
            echo 'PHP cache clearing and service restarts completed!'
          "
          
          echo "Deployment completed successfully!"
      - name: Cleanup
        if: always()
        run: |
          rm -f private_key.pem
          echo "Cleanup completed"