name: EC2 Deployment
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create SSH key
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          # Test connection
          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "echo 'Connection successful!'"
          
          # Create deploy directory
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "sudo mkdir -p /home/ubuntu/app && sudo chown $EC2_USER:$EC2_USER /home/ubuntu/app"
          
          # List local files before copying
          echo "Files to be copied:"
          ls -la
          
          # Copy ALL files to EC2
          scp -r -i private_key.pem ./* ./.* $EC2_USER@$EC2_HOST:/home/ubuntu/app/ 2>/dev/null || true
          
          # Set proper permissions and verify files
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "
            echo 'Uploaded files:' &&
            ls -la /home/ubuntu/app/ &&
            sudo chmod -R 755 /home/ubuntu/app/ &&
            sudo find /home/ubuntu/app/ -type f -exec chmod 644 {} \;
          "
          
          echo "Deployment completed successfully!"

      - name: Cleanup
        if: always()
        run: |
          rm -f private_key.pem
          echo "Cleanup completed"